stages:
  - release

release:
  stage: release
  image: 
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/goreleaser/goreleaser
    entrypoint: ['']
  tags:
    - monitoring-docker
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
    GITLAB_TOKEN: "$GITLAB_ACCESS_TOKEN"
    CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: "gitlab.sofa.dev/aut/iac/private/monitoring/dependency_proxy/containers"
  script:
    - goreleaser release --rm-dist --debug

